s1 = str(input())
s2 = str(input())
s3 = str(input())
s4 = str(input())
s5 = str(input())

p1 = s1.split('#')
print(p1[0])
p2 = s2.split('#')
print(p2[0])
p3 = s3.split('#')
print(p3[0])
p4 = s4.split('#')
print(p4[0])
p5 = s5.split('#')
print(p5[0])