# -*- coding: utf-8 -*-
"""63Lab3P2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D5zf54yJ9z_6psn5SEAlTm-tnReZFy0b
"""

number = int(input("What is your favorite number:"))
print("Your favorite number is "+str(number)+".")
if(number%2==0):
  print("That’s even.")
else:
  print("What an odd!")